import { Inter } from "next/font/google";
import "./globals.css";
import React, { ReactNode } from "react";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.png",
      href: "/favicon.png",
      type: "image/x-icon",
    },
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${inter.className} !overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <div className="w-full md:w-10/12 mx-auto px-5 md:px-0">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
