import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}
        className={`${inter.className} overflow-x-hidden`}>
        <div className="max-w-[1440px] mx-auto px-5 py-5">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
